CREATE TABLE banks (id INTEGER UNSIGNED AUTO_INCREMENT, code CHAR(4), name TEXT, call_center_number TEXT, url TEXT, PRIMARY KEY (id));

INSERT INTO banks (code, name, call_center_number, url) VALUES ('200', 'Bank BTN', '1500286', 'https://www.btn.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('008', 'Bank Mandiri', '14000', 'https://bankmandiri.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('009', 'Bank Negara Indonesia (BNI)', '1500046', 'https://www.bni.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('002', 'Bank Rakyat Indonesia (BRI)', '8080', 'https://bri.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('110', 'Bank BJB', '14049', 'https://www.bankbjb.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('111', 'Bank DKI', NULL, 'https://bankdki.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('112', 'Bank BPD D.I.Y', '1500061', 'https://www.bpddiy.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('113', 'Bank Jateng', '14066', 'https://www.bankjateng.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('114', 'Bank Jatim', '14044', 'https://www.bankjatim.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('115', 'Bank Jambi', NULL, 'https://bankjambi.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('116', 'Bank Aceh', '1500845', 'https://www.bankaceh.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('117', 'Bank Sumut', '14002', 'https://www.banksumut.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('118', 'Bank Sumbar', '150234', 'https://www.banknagari.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('119', 'Bank Kepri', NULL, 'https://www.bankriaukepri.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('120', 'Bank Sumsel and Babel', '1500711', 'https://www.banksumselbabel.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('700', 'Altopay', '14017', 'https://altopay.co.id');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('037', 'Bank Artha Graha', '08001918880', 'https://www.arthagraha.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('536', 'Bank BCA Syariah', '1500888', 'https://www.bcasyariah.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('014', 'Bank Central Asia', '1500888', 'https://www.bca.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('949', 'Bank Chinatrust Indonesia', '08071221111', 'https://www.ctbcbank.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('472', 'Bank Jasa Jakarta', '0216902611', 'https://www.bjj.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('157', 'Bank Maspion', '0315316999', 'https://www.bankmaspion.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('501', 'Bank Royal', '02162864472', 'https://www.royalbank.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('498', 'Bank SBI Indonesia (Indomonex)', '08001724636', 'https://www.sbiindo.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('566', 'Bank Victoria International', '1500977', 'https://www.victoriabank.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('559', 'Bank CNB', '18004923221', NULL);
INSERT INTO banks (code, name, call_center_number, url) VALUES ('567', 'Bank Harda International', '0213841178', NULL);
INSERT INTO banks (code, name, call_center_number, url) VALUES ('042', 'Bank of Tokyo-Mutsubishi UFJ', '0215707809', NULL);
INSERT INTO banks (code, name, call_center_number, url) VALUES ('567', 'PT Allo Bank Indonesia Tbk', '08041104110', 'https://www.allobank.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('076', 'PT Bank Bumi Arta Tbk', '0212300455', 'https://www.bankbba.co.id/bumiarta/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('022', 'PT Bank CIMB Niaga Tbk', '14041', 'https://www.cimbniaga.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('011', 'PT Bank Danamon Indonesia Tbk.', '1500090', 'https://www.danamon.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('161', 'PT Bank Ganesha Tbk', '1500169', 'https://www.bankganesha.co.id');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('164', 'PT Bank ICBC Indonesia', '1500198', 'https://www.icbc.co.id');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('513', 'PT Bank Ina Perdana Tbk', '02134831766', 'https://www.bankina.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('555', 'PT Bank Index Selindo', '1500670', 'https://bankindex.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('542', 'PT Bank Jago Tbk', '1500746', 'https://jago.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('095', 'PT Bank Jtrust Indonesia Tbk.', '1500615', 'https://www.jtrustbank.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('441', 'PT Bank KB Bukopin Tbk.', '14005', 'https://www.bukopin.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('484', 'PT Bank KEB Hana Indonesia', '1500021', 'http://www.hanabank.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('564', 'PT Bank Mandiri Taspen Pos', '14024', 'https://www.bankmantap.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('016', 'PT Bank Maybank Indonesia Tbk.', '1500611', 'https://www.maybank.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('553', 'PT Bank Mayora', '02156966954', 'https://www.bankmayora.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('426', 'PT Bank Mega Tbk.', '1500010', 'https://www.bankmega.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('151', 'PT Bank Mestika Dharma Tbk.', '14083', 'https://www.bankmestika.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('485', 'PT Bank MNC Internasional Tbk', '1500188', 'https://mncbank.co.id/id');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('503', 'PT Bank Nationalnobu Tbk.', '1500278', 'https://www.nobubank.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('490', 'PT Bank Neo Commerce Tbk.', '1500190', 'https://www.bankneocommerce.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('028', 'PT Bank OCBC NISP Tbk.', '1500999', 'https://www.ocbcnisp.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('146', 'PT Bank of India Indonesia Tbk.', '0213500007', 'https://www.boiindonesia.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('526', 'PT Bank Oke Indonesia Tbk.', '0212312633', 'https://www.okbank.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('019', 'PT Bank Panin Tbk.', '1500678', 'https://www.panin.co.id/id');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('013', 'PT Bank Permata Tbk.', '1500111', 'https://www.permatabank.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('167', 'PT Bank QNB Indonesia Tbk.', '0215155155', 'https://qnb.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('494', 'PT Bank Raya Tbk.', '1500494', 'https://bankraya.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('523', 'PT Bank Sahabat Sampoerna', '1500035', 'https://www.banksampoerna.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('535', 'PT Bank Seabank Indonesia', '1500130', 'https://www.seabank.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('153', 'PT Bank Sinarmas Tbk.', '1500153', 'https://www.banksinarmas.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('213', 'PT Bank Tabungan Pensiunan Nasional Tbk.', '1500300', 'https://www.btpn.com');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('023', 'PT Bank UOB Indonesia', '14008', 'https://www.uob.co.id');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('947', 'PT Bank Aladin Syariah Tbk', '02185500947', 'https://aladinbank.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('521', 'PT Bank Bukopin Syariah', '1500666', 'https://www.syariahbukopin.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('425', 'PT Bank Jabar Banten Syariah', '1500727', 'https://www.bjbsyariah.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('147', 'PT Bank Muamalat Indonesia Tbk', '1500016', 'https://www.bankmuamalat.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('517', 'PT Bank Panin Dubai Syariah Tbk', '0216313700', 'https://www.paninbanksyariah.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('451', 'PT Bank Syariah Indonesia Tbk', '14040', 'https://www.mandirisyariah.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('506', 'PT Bank Syariah Mega Indonesia', '02129852222', 'https://www.megasyariah.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('547', 'PT Bank Tabungan Pensiunan Nasional Syariah', '0211500300', 'https://www.btpnsyariah.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('031', 'Citibank NA', '0212529999', 'https://www.citibank.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('061', 'PT Bank ANZ Indonesia', '08041000269', 'https://institutional.anz.com/markets/indonesia/id');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('054', 'PT Bank Capital Indonesia Tbk', '02127938989', 'https://www.bankcapital.co.id/id');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('950', 'PT Bank Commonwealth', '1500030', 'https://www.commbank.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('046', 'PT Bank DBS Indonesia', '1500327', 'https://www.dbs.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('087', 'PT Bank HSBC Indonesia', '1500700', 'https://www.hsbc.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('945', 'PT Bank IBK Indonesia, Tbk.', '1500978', NULL);
INSERT INTO banks (code, name, call_center_number, url) VALUES ('069', 'PT Bank of China Indonesia', '0215200986', 'https://www.bankofchina.co.id');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('152', 'PT Bank Shinhan Indonesia', '1500881', 'https://www.shinhan.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('212', 'PT Bank Woori Saudara Indonesia', '1500012', 'https://www.bankwoorisaudara.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('050', 'PT Standard Chartered Bank Indonesia', '02157999988', 'https://www.sc.com/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('867', ' PT BPR Eka Bumi Artha', NULL, NULL);
INSERT INTO banks (code, name, call_center_number, url) VALUES ('028', 'PT BPR Danagung Abadi', NULL, NULL);
INSERT INTO banks (code, name, call_center_number, url) VALUES ('028', 'PT BPR Danagung Bakti', NULL, NULL);
INSERT INTO banks (code, name, call_center_number, url) VALUES ('028', 'PT BPR Danagung Ramulti', NULL, NULL);
INSERT INTO banks (code, name, call_center_number, url) VALUES ('688', 'PT BPR Karyajatnika Sadaya', '0224556600', 'https://bprks.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('600', 'PT BPR Supra Artapersada', '0266237070', 'http://www.bprsupra.co.id/');
INSERT INTO banks (code, name, call_center_number, url) VALUES ('911', 'PT Fintek Karya Nusantara', '118', NULL);
INSERT INTO banks (code, name, call_center_number, url) VALUES ('789', 'PT Indosat Tbk', '02130003000', NULL);
